import type { LucideIcon } from "lucide-react";
import {
  AppWindow,
  Blocks,
  BookOpen,
  Box,
  Braces,
  Brush,
  Calculator,
  Camera,
  Code,
  Dices,
  FileText,
  Film,
  FolderOpen,
  Gamepad2,
  GitBranch,
  Globe,
  Image,
  MessageSquare,
  Music,
  Palette,
  PenTool,
  Presentation,
  Rocket,
  Send,
  Sword,
  Table2,
  Terminal,
  Trophy,
  Zap,
} from "lucide-react";

export const ICONS = {
  appWindow: AppWindow,
  blocks: Blocks,
  bookOpen: BookOpen,
  braces: Braces,
  brush: Brush,
  calculator: Calculator,
  camera: Camera,
  code: Code,
  cube: Box,
  dices: Dices,
  fileText: FileText,
  film: Film,
  folderOpen: FolderOpen,
  gamepad2: Gamepad2,
  gitBranch: GitBranch,
  globe: Globe,
  image: Image,
  messageSquare: MessageSquare,
  music: Music,
  palette: Palette,
  penTool: PenTool,
  presentation: Presentation,
  rocket: Rocket,
  send: Send,
  sword: Sword,
  table2: Table2,
  terminal: Terminal,
  trophy: Trophy,
  zap: Zap,
} as const satisfies Record<string, LucideIcon>;

export type IconKey = keyof typeof ICONS;

export const ICON_CHOICES: IconKey[] = [
  "appWindow",
  "code",
  "terminal",
  "braces",
  "gamepad2",
  "cube",
  "trophy",
  "sword",
  "rocket",
  "blocks",
  "globe",
  "bookOpen",
  "fileText",
  "table2",
  "presentation",
  "calculator",
  "music",
  "messageSquare",
  "film",
  "camera",
  "image",
  "brush",
  "palette",
  "penTool",
  "dices",
  "send",
  "gitBranch",
  "folderOpen",
];

export function resolveIcon(key: string): LucideIcon {
  return ICONS[key as IconKey] ?? AppWindow;
}